"""add_user_balance

Revision ID: 4d3146c0ecee
Revises: 617ec3edf754
Create Date: 2025-02-23 13:57:05.990895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d3146c0ecee"
down_revision: Union[str, None] = "617ec3edf754"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("balance", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "balance")
    # ### end Alembic commands ###
