START = ("start", "🔄 Перезапустить бота")
MENU = ("menu", "👨🏻‍💻 Главное меню")
KEYS = ("keys", "🔑 Мои ключи")
BALANCE = ("balance", "💰 Пополнить баланс")
BUY = ("buy", "💲 Оплатить ключ")
INSTRUCTION = ("instruction", "💡 Инструкция")
HELP = ("help", "❓ Поддержка")
INVITE = ("ref", "👥 Пригласить друга")