from settings import settings

BUY = "💲 Оплатить ключ"
BALANCE = "💰 Пополнить баланс"
KEYS = "🔑 Мои ключи"
PAYMENTS = "🧾️ Платежи"
ADMIN = "⚙️️ Администратор"
NOTIFY = "📢 Рассылка"
STATS = "📊 Статистика"
BACK = "🔙 назад"
TRIAL_KEY = f"🎁 Бесплатно на {settings.trial_days} дней"
NEW_KEY = "🔑 Купить новый ключ"
EXTEND_KEY = "➕ Продлить ключ"
DELETE_KEY = "🗑 Удалить ключ"
EXTRA_TRAFFIC = "🔁 Купить доп. трафик"
ANDROID = "🤖 Android"
IOS = "📱 iOS"
MACOS = "💻 macOS"
WINDOWS = "🖥️ Windows"
NOTIFICATION = "ℹ️"
